import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Falsemed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="global-wrap">
          {children}
          <footer className="footer">Footer</footer>
        </div>
        {/* <div style={{width: "100%", color: "white", backgroundColor: 'black', textAlign: 'center', height: "100px", lineHeight: "100px"}}>Footer</div> */}
      </body>
    </html>
  );
}
